extends Node

signal request_use_item(item_id: StringName, cell: Vector2i)
signal request_harvest(cell: Vector2i)

signal time_changed(day: int, hour: int, minute: int)
signal day_passed(new_day: int)
signal season_changed(season_name: String)
signal weather_changed(weather_id: StringName)

signal money_changed(new_amount: int)
signal inventory_changed()
signal selected_slot_changed(index: int)
signal stamina_changed(current: float, maximum: float)
signal watering_can_changed(current: int, maximum: int)

signal tile_tilled(cell: Vector2i)
signal tile_watered(cell: Vector2i)
signal crop_planted(cell: Vector2i, crop_id: StringName)
signal crop_grew(cell: Vector2i, stage: int)
signal crop_harvested(cell: Vector2i, produce_id: StringName, amount: int)
signal crop_inspected(crop_id: StringName, stage: int, mature_stage: int, watered_days: int, days_per_stage: int, harvestable: bool)

signal collection_discovered(produce_id: StringName)
signal fish_discovered(fish_item_id: StringName)
signal recipe_discovered(recipe_id: StringName)
signal achievement_unlocked(achievement_id: StringName, title: String)
signal save_load_started()

signal game_saved(slot: int)
signal game_loaded(slot: int)
signal request_open_shop()
signal request_open_cooking()
signal dialogue_requested(npc_data: Resource)
signal dialogue_active_changed(active: bool)
signal friendship_upgraded(npc_name: String, new_level: int)
signal fishing_started(fishing_spot: Node)
signal fish_caught(fish_data: Resource)
signal fishing_leveled_up(new_level: int)
signal fishing_xp_gained(amount: int, source: StringName)
signal bait_used(bait_id: StringName)
signal rod_changed(new_rod_id: StringName)
signal buff_changed()
